name: Bug Report
# title: " "
description: Problems with Pytorch-Wildlife 
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/microsoft/CameraTraps/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the Pytorch-Wildlife [issues](https://github.com/microsoft/CameraTraps/issues) and found no similar bug report.
          required: true

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        💡 ProTip! Include as much information as possible (error messages, screenshots, logs, tracebacks, etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please specify the software and hardware you used to produce the bug.
      placeholder: |
        - PytorchWildlife: 1.0.2.4
        - OS: Ubuntu 18.04
        - Python: 3.8.0
    validations:
      required: false

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        This is referred to by community members as creating a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/microsoft/CameraTraps/pulls) (PR) to help contribute Pytorch-Wildlife for everyone, especially if you have a good understanding of how to implement a fix or feature.
      options:
        - label: Yes I'd like to help by submitting a PR!